### ISSUE TITLE
s3pay touch?

### ISSUE THREAD

**Issue by perrygeo** [mapbox/s3pay#2]
I'm looking for a way to combine the functionality of [s3touch](https://github.com/mapbox/s3touch) with requester-pays s3 objects. Is this possible? Does the `aws` cli already provide similar functionality? And is this repo the best place for it?

@rclark

**Comment by rclark** [comment]
s3touch makes headObject requests and listObjects requests. s3pay includes functions to make these requests while including the `x-amz-request-payer` header, but it doesn't export these functions in a way that s3touch could `require`. 

I think that this could be done by:
- pull [the headObject, getObject, and listObject functions](https://github.com/mapbox/s3pay/blob/master/s3pay.js#L61-L132) out of s3pay.js into an `index.js` file and add them to `module.exports`
- `require` them in order to use them in s3pay.js
- add a CLI option to s3touch that toggles on requester-pays mode, and depend on the functions defined here.

> Does the aws cli already provide similar functionality?

It may -- I believe that when I wrote this lib it was not possible or at least not obvious how to include the appropriate headers in an awscli command. Trying to drop that into s3touch though would basically be a rewrite of that lib.

cc @virginiayung

**Comment by perrygeo** [comment]
I'll take this one on, we've got a stopgap bash script that will do for the short term but I'll plan on working on this over the next 2 weeks.

**Comment by perrygeo** [comment]
After looking at `s3pay` and it's `headObject` function, I'm not sure how useful it would be without a bit of refactoring. Currently [the `headObject` function](https://github.com/mapbox/s3pay/blob/master/s3pay.js#L79-L100) also calls getObject on success.

I think the solution could be much simpler and would only involve adding `RequestPayer: 'requester'` to the parameters to `s3.headObject` in s3touch. ([docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#headObject-property))

Closing this ticket, PR coming for s3touch...
